name: License Analysis with maven and dash

on:
  workflow_call:
    inputs:
      java_version:
        description: 'The Java version to use'
        required: false
        type: string
        default: '17'
      dash_project_id:
        description: 'The Dash project ID'
        required: false
        type: string
        default: ''
      dash_repo:
        description: 'The Dash repository URL'
        required: false
        type: string
        default: ''
      create-review:
        description: 'Create a review for the license analysis'
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: false

permissions:
  pull-requests: read
  contents: write

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'zulu'
          cache: maven

      - name: validate inputs
        id: validate-inputs
        if: ${{ inputs.create-review }}
        run: |
          if [ "${{ inputs.create-review }}" = "true" ]; then
            if [ -z "${{ secrets.token }}" ]; then
              echo "Token is required for creating a review but not provided."
              exit 1
            fi
            if [ -z "${{ inputs.dash_project_id }}" ]; then
              echo "dash_project_id=${GITHUB_REPOSITORY//\//_}" >> $GITHUB_ENV
            else
              echo "dash_project_id=${{ inputs.dash_project_id }}" >> $GITHUB_ENV
            fi
            if [ -z "${{ inputs.dash_repo }}" ]; then
              echo "dash_repo=http://github.com/${GITHUB_REPOSITORY}" >> $GITHUB_ENV
            else
              echo "dash_repo=${{ inputs.dash_repo }}" >> $GITHUB_ENV
            fi
          fi

      - name: Build with Maven and check dependencies with dash
        run: |
           if [ "${{ inputs.create-review }}" = "true" ]; then
              mvn --batch-mode --update-snapshots verify -Ddash.projectId=${{ inputs.dash_project_id }} -Ddash.repo=${{ inputs.dash_repo }} -Ddash.iplab.token=${{ secrets.token }} -P dash
           else
              mvn --batch-mode --update-snapshots verify -P dash
           fi

      - name: Ensure DEPENDENCIES file is reflecting the current state
        run: |
          mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES-gen -P dash
          diff DEPENDENCIES DEPENDENCIES-gen || echo "DEPENDENCIES file differs from DEPENDENCIES-gen"

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: 'target/dash/summary'
          name: 'license-analysis-summary'