name: SonarCloud Analysis

on:
  workflow_call:
    inputs:
      java_version:
        description: 'The Java version to use'
        required: false
        type: string
        default: '17'
      sonar_project_key:
        description: 'The SonarCloud project key'
        required: false
        type: string
        default: ''
      sonar_organization:
        description: 'The SonarCloud organization'
        required: false
        type: string
        default: ''
    secrets:
      token:
        required: true

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Sonar is enabled
        id: sonar-check
        run: |
          if [[ "${{ secrets.token }}" == "" ]]; then
            echo "SONAR_TOKEN is not set. Skipping Sonar analysis."
            echo "sonar_enabled=false" >> $GITHUB_ENV
          else
            echo "SONAR_TOKEN is set. Sonar analysis will be performed."
            echo "sonar_enabled=true" >> $GITHUB_ENV
          fi

      - name: Checkout code
        if: ${{ env.sonar_enabled == 'true' }}
        uses: actions/checkout@v4

      - name: Compute Sonar Key
        id: compute-sonar-key
        if: ${{ env.sonar_enabled == 'true'}}
        run: |
            if [[ "${{ inputs.sonar_project_key }}" == "" ]]; then
                 echo "sonar_key=${GITHUB_REPOSITORY//\//_}" >> $GITHUB_ENV
            else
                echo "sonar_key=${{ inputs.sonar_project_key }}" >> $GITHUB_ENV
            fi
      - name: Compute Sonar Organization
        id: compute-sonar-org
        if: ${{ env.sonar_enabled == 'true'}}
        run: |
          if [[ "${{ inputs.sonar_organization }}" == "" ]]; then
               echo "sonar_organization=${{ github.repository_owner }}" >> $GITHUB_ENV
          else
              echo "sonar_organization=${{ inputs.sonar_organization }}" >> $GITHUB_ENV
          fi
      - name: Set up JDK
        if: ${{ env.sonar_enabled == 'true' }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: zulu
          cache: maven

      - name: Cache Maven dependencies
        if: ${{ env.sonar_enabled == 'true' }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run SonarCloud Analysis
        if: ${{ env.sonar_enabled == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.token }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ env.sonar_key }} \
            -Dsonar.organization=${{ env.sonar_organization }} \
            -Dsonar.login=${{ secrets.token }}